cxf:
  path: /
  servlet.init:
    service-list-path: /info

management:
  security:
    enabled: false

server:
  port: ${PORT:38081}
  servlet-path: /system

spring:
  profiles:
      active: level1
  boot:
    admin:
      client:
        enable: false
      url: http://localhost:9666
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=Oracle
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maxLifetime: 500
        rewriteBatchedStatements: true
        idle-timeout: 10000
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create